include: package:flutter/analysis_options_user.yaml

linter:
  rules:
    - unnecessary_null_in_if_null_operators
    - unnecessary_new
    - unnecessary_const
    - prefer_relative_imports
    - prefer_final_fields
    - prefer_single_quotes
    - avoid_redundant_argument_values
    - prefer_void_to_null
    - valid_regexps
    - no_logic_in_create_state
    - avoid_init_to_null
    - avoid_returning_null
    - avoid_types_on_closure_parameters
    - camel_case_types
    - curly_braces_in_flow_control_structures
    - file_names
    - prefer_initializing_formals
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_null_aware_operators
    - prefer_spread_collections
    - prefer_typing_uninitialized_variables
    - unnecessary_await_in_return
    - prefer_mixin
    - avoid_bool_literals_in_conditional_expressions
    - unnecessary_lambdas
    - prefer_conditional_assignment
    - prefer_collection_literals
    - parameter_assignments
    - prefer_foreach
    - prefer_if_elements_to_conditional_expressions
    - prefer_is_not_operator
    - unnecessary_null_aware_assignments
    - prefer_int_literals
    - prefer_final_in_for_each
